### ISSUE TITLE
App Can't Open

### ISSUE THREAD

**Issue by MikeKe254** [logicpulse/logicPOS#19]
I am trying to open the app but its not opening. I installed the latest Visual c++ redistributable and still doesn't work. I am running on windows 8.1. Below is the logicPos Log. 

`2022-04-20 20:08:14,084 [DEBUG] logicpos.MainApp : Use configuration file: [C:\Program Files (x86)\Logicpulse\logicpos\logicpos.exe.Config]
2022-04-20 20:08:14,446 [ERROR] logicpos.MainApp : Missing Culture in DataBase or DB not created yet, using en-US from config.
2022-04-20 20:08:14,446 [DEBUG] logicpos.MainApp : void StartApp() :: Show 'loading'
2022-04-20 20:08:14,524 [ERROR] logicpos.MainApp : Method not found: '!!0[] System.Array.Empty()'.
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at logicpos.Utils.GetThreadDialog(Window pSourceWindow, Boolean dbExists, String backupProcess)
   at logicpos.Utils.?????????????????????????????(Object , Boolean dbExists, Object )
   at logicpos.Utils.GetThreadDialog(Window pSourceWindow, Boolean dbExists)
   at logicpos.MainApp.?????????????????????????????(Object , Boolean dbExists)
   at logicpos.MainApp.FirstSteps()
2022-04-20 20:08:14,540 [ERROR] logicpos.MainApp : Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at logicpos.MainApp.?????????????????????????????(Object )
   at logicpos.MainApp.FirstSteps()
   at logicpos.MainApp.Main(String[] args)`

As seen the main error is `Object reference not set to an instance of an object`  

How do I fix that please?

**Comment by MikeKe254** [comment]
Update: Fixed this by updating .net framework to v4.8
